apiVersion: 1

datasources:
  - name: SensorDB
    type: mysql
    access: proxy
    url: localhost:3306
    database: sensor_db
    user: grafana_user
    secureJsonData:
      password: "grafana1234"
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      timescaledb: false
    isDefault: true
    editable: true
